### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by grisaiakaziki** [uzh-rpg/EvDeblurNeRF#1]
I have an NVIDIA RTX 3090 graphics card, and I'm encountering a torch.cuda.OutOfMemoryError: CUDA out of memory error. How can I successfully run this project?What changes do I need to make?

**Comment by grisaiakaziki** [comment]
I encountered this problem when training reached iteration 1199.

**Comment by marcocannici** [comment]
Dear @grisaiakaziki,
thank you for your interest in this project. 

At iteration 1199, the training code activates L_blur (Eq 8), which renders blurred images as the average of multiple latent sharp images. As a result, the VRAM utilization increases. Usually, our code requires more than the 24GB VRAM of the RTX 3090. 

You have a few options to lower the VRAM utilization:

- Set `--chunk` and `--netchunk` to a lower value. These parameters control how many samples are processed together during rendering. They only impact training time, not performance.
- Lower the batch sizes. You can set `--N_rand` to change the batch size of the color losses and `--events_N_rand` to change that of the event losses. Lowering these values might impact performance.
- Lower `--kernel_ptnum`, which controls the number of latent images used to render blurry colors in L_blur. Lowering this value might also lower performance.

Since the code stops just after L_blur is enabled, I believe playing with `--N_rand` might be the most effective way of lowering VRAM in your case. I did a quick test, and setting these parameters seems to lower memory usage to around 22GB on the factory sequence: `--chunk 1024 --netchunk 1024 --N_rand 820`.

Notice that we run all our experiments with `--N_rand 1024`, so using a lower value might give you lower performance. You might also experience a slower training time because of the `chunk` and `netchunk` parameters. I suggest you to adjust these values until you find a good configuration for your case.

**Comment by grisaiakaziki** [comment]
Thank you for your response, it has helped me a lot. I hope you can produce even better work in the future.

**Comment by marcocannici** [comment]
Perfect! I'll close this issue then.

**Comment by marcocannici** [comment]
Perfect! I'll close this issue then.
